# Generated by Django 4.2.7 on 2023-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitVegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
                ('title', models.CharField(max_length=255)),
                ('сreated', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthyFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
                ('title', models.CharField(max_length=255)),
                ('сreated', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FruitVegetable',
        ),
        migrations.DeleteModel(
            name='HelathyFood',
        ),
        migrations.AlterField(
            model_name='babyfood',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='babyfood',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='balakleya',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='balakleya',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bread',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bread',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='confectionary',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='confectionary',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='frozenproduct',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='frozenproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meat',
            name='image',
            field=models.ImageField(upload_to='%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='meat',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milk',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nonfoodproduct',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='nonfoodproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petproduct',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='petproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='teacoffe',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teacoffe',
            name='price',
            field=models.FloatField(),
        ),
    ]
