# Generated by Django 4.2.7 on 2023-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0002_fruitvegetables_healthyfood_delete_fruitvegetable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
